[features]
seeds = false
[programs.devnet]
pda_test = "A9RfydetpSqT5rLRZNmeVaeyqG84tXm8cNZkn6Zy1817"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/simeon/.config/solana/id.json"

[scripts]
go = "ts-node nieuwe_client.ts"
comp = "tsc -p . && node nieuwe_client.js"
